"""Add RBAC models

Revision ID: 049c7e1b14c1
Revises: b4f2d7a9c601
Create Date: 2026-04-13 08:34:05.652687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '049c7e1b14c1'
down_revision = 'b4f2d7a9c601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marcas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('users_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    with op.batch_alter_table('rsi_bodegas', schema=None) as batch_op:
        batch_op.alter_column('bodega',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.drop_column('codigotiendapos')
        batch_op.drop_column('estienda')
        batch_op.drop_column('abrev')
        batch_op.drop_column('cia')

    with op.batch_alter_table('rsi_inv_pordia', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=False)
        batch_op.alter_column('cantidad',
               existing_type=mysql.DECIMAL(precision=18, scale=5),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True,
               existing_server_default=sa.text("'0.00000'"))
        batch_op.alter_column('costo',
               existing_type=mysql.DECIMAL(precision=18, scale=5),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True,
               existing_server_default=sa.text("'0.00000'"))
        batch_op.alter_column('precio',
               existing_type=mysql.DECIMAL(precision=18, scale=5),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True,
               existing_server_default=sa.text("'0.00000'"))
        batch_op.alter_column('ventapromedio',
               existing_type=mysql.DECIMAL(precision=18, scale=5),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('cantidadcontabilidad',
               existing_type=mysql.DECIMAL(precision=18, scale=5),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True,
               existing_server_default=sa.text("'0.00000'"))
        batch_op.alter_column('fechaultentrada',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('fechaultcompra',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('cantidadultcompra',
               existing_type=mysql.DECIMAL(precision=18, scale=5),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('secciones', schema=None) as batch_op:
        batch_op.alter_column('rimith_dept',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('secciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('rimith_dept',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=True)

    with op.batch_alter_table('rsi_inv_pordia', schema=None) as batch_op:
        batch_op.alter_column('cantidadultcompra',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=mysql.DECIMAL(precision=18, scale=5),
               existing_nullable=True)
        batch_op.alter_column('fechaultcompra',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('fechaultentrada',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('cantidadcontabilidad',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=mysql.DECIMAL(precision=18, scale=5),
               existing_nullable=True,
               existing_server_default=sa.text("'0.00000'"))
        batch_op.alter_column('ventapromedio',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=mysql.DECIMAL(precision=18, scale=5),
               existing_nullable=True)
        batch_op.alter_column('precio',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=mysql.DECIMAL(precision=18, scale=5),
               existing_nullable=True,
               existing_server_default=sa.text("'0.00000'"))
        batch_op.alter_column('costo',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=mysql.DECIMAL(precision=18, scale=5),
               existing_nullable=True,
               existing_server_default=sa.text("'0.00000'"))
        batch_op.alter_column('cantidad',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=mysql.DECIMAL(precision=18, scale=5),
               existing_nullable=True,
               existing_server_default=sa.text("'0.00000'"))
        batch_op.alter_column('fecha',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('rsi_bodegas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cia', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=True))
        batch_op.add_column(sa.Column('abrev', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=True))
        batch_op.add_column(sa.Column('estienda', mysql.TINYINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('codigotiendapos', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=True))
        batch_op.alter_column('bodega',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               existing_nullable=False)

    op.drop_table('users_roles')
    op.drop_table('roles_permissions')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('marcas')
    # ### end Alembic commands ###
