"""full schema v2 catalog tables

Revision ID: fed909aa9cdd
Revises: 
Create Date: 2026-03-05 15:41:22.618495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fed909aa9cdd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=250), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalog_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_items_category'), ['category'], unique=False)

    op.create_table('clasificaciones_nc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('grupo', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('marcas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('secciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider_tipo', sa.String(length=50), nullable=True),
    sa.Column('rimith_dept', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('non_conformities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nc_number', sa.String(length=50), nullable=False),
    sa.Column('date_detected', sa.Date(), nullable=False),
    sa.Column('time_detected', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('detected_by_type', sa.String(length=50), nullable=True),
    sa.Column('empresa', sa.String(length=150), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('provider_tipo', sa.String(length=50), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('rimith_dept', sa.String(length=50), nullable=True),
    sa.Column('section', sa.String(length=100), nullable=True),
    sa.Column('deviation_type', sa.String(length=50), nullable=True),
    sa.Column('gravity', sa.String(length=50), nullable=True),
    sa.Column('classification', sa.String(length=250), nullable=True),
    sa.Column('cause', sa.String(length=100), nullable=True),
    sa.Column('motive', sa.String(length=100), nullable=True),
    sa.Column('prerequisite', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('product_affected', sa.String(length=200), nullable=True),
    sa.Column('marca', sa.String(length=150), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('lot', sa.String(length=100), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('total_units', sa.Float(), nullable=True),
    sa.Column('total_usd', sa.Float(), nullable=True),
    sa.Column('affects_consumer', sa.Boolean(), nullable=True),
    sa.Column('affects_inocuity', sa.Boolean(), nullable=True),
    sa.Column('affects_quality', sa.Boolean(), nullable=True),
    sa.Column('nc_product_status', sa.String(length=100), nullable=True),
    sa.Column('evaluations', sa.Text(), nullable=True),
    sa.Column('evaluation_description', sa.Text(), nullable=True),
    sa.Column('action_1', sa.Text(), nullable=True),
    sa.Column('action_2', sa.Text(), nullable=True),
    sa.Column('action_3', sa.Text(), nullable=True),
    sa.Column('corrective_action', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('closure_date', sa.Date(), nullable=True),
    sa.Column('closed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('non_conformities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_non_conformities_nc_number'), ['nc_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('non_conformities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_non_conformities_nc_number'))

    op.drop_table('non_conformities')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('secciones')
    op.drop_table('providers')
    op.drop_table('marcas')
    op.drop_table('empresas')
    op.drop_table('departments')
    op.drop_table('clasificaciones_nc')
    with op.batch_alter_table('catalog_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalog_items_category'))

    op.drop_table('catalog_items')
    # ### end Alembic commands ###
